# Generated by Django 4.1.10 on 2023-07-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='namr',
            new_name='name',
        ),
    ]
